<?php
namespace app\components\widgets;
use yii\base\Widget;

/**
 * Created by PhpStorm.
 * User: evgenijampleev
 * Date: 22.06.17
 * Time: 12:39
 */
class MyWidget extends Widget {

    public function run(){
        echo "My widget!";
        //parent::run(); // TODO: Change the autogenerated stub
    }


}